<?php
$site_version = '0.1';
$site_title = 'FantaRia';
$log = 'true';

$saggezza = array
        (
          '0' => "non rinunciare ai tuoi sogni, continua a dormire.",
          '1' => "le opportunità passano volando, per questo bisogna saltare sempre.",
          '2' => "se la montagna viene a te... è che sta cadendo una frana!",
          '3' => 'non è bello ciò che è bello, figuriamoci ciò che è brutto.',
          '4' => 'chi la fa, l’aspetti. Chi non la fa, si purghi.',
          '5' => 'non rimandare a domani quello che puoi rimandare a dopodomani.',
          '6' => 'una mela al giorno… fanno 365 mele all’anno.',
          '7' => 'ci sono momenti in cui va bene tutto; non ti spaventare, non dura.',
          '8' => 'se vai a lavorare canticchiando felice hai 3 possibilità: sei miliardario, ti droghi o sei uno dei sette nani.',
      );

?>
